import { expect, test } from '@playwright/test'

test.skip(process.env.RUN_SALES_E2E !== 'true', 'requires pnpm db:reset and the isolated local Supabase fixture')
test.use({ viewport: { width: 390, height: 844 } })

test('nhân viên hoàn thành bán sỉ và bán lẻ trên điện thoại', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('Tên tài khoản').fill('nhanvien')
  await page.getByLabel('Mật khẩu').fill('123456')
  await page.getByRole('button', { name: /Vào hệ thống|Đăng nhập/ }).click()
  await page.waitForURL('**/')
  await page.goto('/sales/new/wholesale')
  await page.getByLabel('Khách hàng đầu mối').selectOption({ index: 1 })
  await expect(page.getByText('7.000 VNĐ/bao')).toBeVisible()
  await page.getByLabel('Số lượng bao').fill('10')
  await expect(page.getByText('70.000 VNĐ')).toBeVisible()
  await page.getByLabel('Tiền nhận ngay').fill('20000')
  await page.getByRole('button', { name: 'Lưu Đơn Bán Sỉ' }).click()
  await expect(page.getByRole('status')).toContainText('Đã lưu thành công đơn bán sỉ')
  await page.goto('/sales/new/retail')
  await page.getByLabel('Mã ca').fill('E2E-DAY')
  await page.getByLabel('Số bao dòng 1').fill('5')
  await page.getByLabel('Đơn giá dòng 1').fill('12000')
  await page.getByRole('button', { name: 'Thêm mức giá' }).click()
  await page.getByLabel('Số bao dòng 2').fill('3')
  await page.getByLabel('Đơn giá dòng 2').fill('10000')
  await page.getByLabel('Tổng tiền đã thu').fill('90000')
  await page.getByRole('button', { name: 'Lưu bán lẻ' }).click()
  await expect(page.getByRole('status')).toContainText('Đã lưu thành công tổng hợp bán lẻ')
})

test('nhân viên xem được giao dịch của ngày vận hành cũ', async ({ page, context }) => {
  await page.goto('/login')
  await page.getByLabel('Tên tài khoản').fill('quanly')
  await page.getByLabel('Mật khẩu').fill('123456')
  await page.getByRole('button', { name: /Vào hệ thống|Đăng nhập/ }).click()
  await page.waitForURL('**/')

  await page.goto('/sales/new/wholesale')
  await page.getByLabel('Khách hàng đầu mối').selectOption({ index: 1 })
  await page.getByLabel('Dùng giờ hiện tại').uncheck()
  await page.getByLabel('Thời gian thực tế').fill('2026-09-05T20:30')
  await page.getByLabel('Giá sỉ thực tế mỗi bao').fill('7000')
  await page.getByLabel('Số lượng bao').fill('4')
  await page.getByLabel('Tiền nhận ngay').fill('28000')
  await page.getByRole('button', { name: 'Lưu Đơn Bán Sỉ' }).click()
  await expect(page.getByRole('status')).toContainText('Đã lưu thành công đơn bán sỉ')

  await context.clearCookies()
  await page.goto('/login')
  await page.getByLabel('Tên tài khoản').fill('nhanvien')
  await page.getByLabel('Mật khẩu').fill('123456')
  await page.getByRole('button', { name: /Vào hệ thống|Đăng nhập/ }).click()
  await page.waitForURL('**/')

  await page.goto('/sales?day=2026-09-05')
  await expect(
    page.getByRole('heading', { name: 'Giao dịch ngày 05/09/2026' }),
  ).toBeVisible()
  await expect(page.getByText('Đầu mối E2E')).toBeVisible()
  await expect(page.getByLabel('Tổng hợp bán hàng trong ngày').getByText('28.000 đ').first()).toBeVisible()
  await expect(page.getByRole('link', { name: 'Về hôm nay để nhập' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Nhập Bán Sỉ' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Nhập Bán Lẻ' })).toHaveCount(0)

  await page.getByLabel('Chọn ngày vận hành').fill('2026-09-01')
  await page.getByRole('link', { name: 'Ngày trước', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Giao dịch ngày 04/09/2026' })).toBeVisible()
  await expect(page.getByLabel('Chọn ngày vận hành')).toHaveValue('2026-09-04')
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Giao dịch ngày 05/09/2026' })).toBeVisible()
  await expect(page.getByLabel('Chọn ngày vận hành')).toHaveValue('2026-09-05')
  await page.getByLabel('Chọn ngày vận hành').fill('2026-09-02')
  await page.getByRole('button', { name: 'Mở ngày' }).click()
  await expect(page).toHaveURL(/\/sales\?day=2026-09-02$/)
  await expect(page.getByRole('heading', { name: 'Giao dịch ngày 02/09/2026' })).toBeVisible()
})
